
 - name: "Install node.js"
   become: true
   shell: |
     curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
     sudo apt install -y nodejs



 - name: "Install PM2 Globally"
   npm: 
    name: pm2 
    global: yes  
    production: yes
    state: present 
