
- name: "Creates backend app directory"
  file:
    path: ~/backend-app
    state: directory

- name: "Unarchive backend files"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app


- name: "Installing Node Dependencies"
  shell:
    cd ~/backend-app
    npm i    
- name: "Executing Node app with PM2"
  shell: |
    cd ~/backend-app/dist
    export NODE_ENV=production
    export VERSION=1
    export TYPEORM_CONNECTION=postgres
    export TYPEORM_MIGRATIONS_DIR=./src/migrations
    export TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts
    export TYPEORM_MIGRATIONS=./src/migrations/*.ts
    export TYPEORM_HOST=localhost
    export TYPEORM_PORT=5532
    export TYPEORM_USERNAME=postgres
    export TYPEORM_PASSWORD=password
    export TYPEORM_DATABASE=glee
    pm2 stop default
    pm2 start main.js
  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  shell: |
    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save

#